server:
  port: 8080

spring:
  application:
    name: daisy-keycloak
  # Keycloak Config
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER}
          jwk-set-uri: ${JWKS}

jwt:
  auth:
    converter:
      principal-attribute: preferred_username
      resource-id: daisy-client-api-rest

logging:
  level:
    org:
      keycloak: DEBUG